import sys
import os
import hashlib

def get_source_hash(source_files):
    hasher = hashlib.sha256()
    all_files = []
    for src in source_files:
        if os.path.isfile(src):
            all_files.append((os.path.basename(src), src))
        elif os.path.isdir(src):
            parent_dir = os.path.dirname(src)
            for root, _, filenames in os.walk(src):
                for name in filenames:
                    filepath = os.path.join(root, name)
                    relpath = os.path.relpath(filepath, parent_dir)
                    all_files.append((relpath, filepath))
                    
    all_files.sort(key=lambda x: x[0])
    for relpath, filepath in all_files:
        hasher.update(relpath.encode('utf-8'))
        with open(filepath, 'rb') as fp:
            hasher.update(fp.read())
    return hasher.hexdigest(), [x[0] for x in all_files]

def check_duplicate(project_name, source_files):
    script_dir = os.path.dirname(os.path.abspath(__file__))
    base_dir = os.path.dirname(script_dir)
    repo_base = os.environ.get("REPOSITORIES_DIR", os.path.join(base_dir, "repositories"))
    project_dir = os.path.join(repo_base, project_name)

    if not os.path.exists(project_dir):
        print("NEW_PROJECT")
        sys.exit(0)

    # get latest version
    versions = [d for d in os.listdir(project_dir) if os.path.isdir(os.path.join(project_dir, d))]
    if not versions:
        print("NEW_PROJECT")
        sys.exit(0)
        
    latest_version = sorted(versions)[-1]
    latest_version_dir = os.path.join(project_dir, latest_version)

    # get hashes
    src_hash, src_relpaths = get_source_hash(source_files)
    
    tgt_hasher = hashlib.sha256()
    
    all_match = True
    for relpath in src_relpaths:
        tgt_file = os.path.join(latest_version_dir, relpath)
        if not os.path.exists(tgt_file):
            all_match = False
            break
            
        tgt_hasher.update(relpath.encode('utf-8'))
        with open(tgt_file, 'rb') as fp:
            tgt_hasher.update(fp.read())
            
    if not all_match:
        print("CHANGED")
        sys.exit(0)
        
    # Check if target has EXTRA files (e.g. if a file was deleted in source_files, it should be CHANGED)
    # Exclude README.md or CHANGELOG.md that might have been generated by the agent
    tgt_files = []
    for root, _, filenames in os.walk(latest_version_dir):
        for name in filenames:
            relpath = os.path.relpath(os.path.join(root, name), latest_version_dir)
            if relpath not in ["README.md", "CHANGELOG.md"]:
                tgt_files.append(relpath)
                
    # If the number of files don't match (ignoring agent metadata), it's a change
    if len(tgt_files) != len(src_relpaths):
        print("CHANGED")
        sys.exit(0)
        
    if src_hash == tgt_hasher.hexdigest():
        print("DUPLICATE")
    else:
        print("CHANGED")

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--project", required=True)
    parser.add_argument("--files", nargs="*", default=[])
    args = parser.parse_args()
    check_duplicate(args.project, args.files)
